name: Build and Package EpanouiDent

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build executable for ${{ matrix.os }}
      run: |
        python setup.py build

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: myapp-${{ matrix.os }}
        path: build/exe.${{ matrix.os }}-*/
