name: Build and Package EpanouiDent

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build executable for ${{ matrix.os }}
      run: |
        python setup.py build

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: epanouident-${{ matrix.os }}
        path: |
          ${{ matrix.os == 'ubuntu-latest' && 'build/exe.linux-x86_64-3.11/*' || '' }}
          ${{ matrix.os == 'macos-latest' && 'build/exe..macosx-10.9-universal2-3.11/*' || '' }}
          ${{ matrix.os == 'windows-latest' && 'build/exe.win-amd64-3.11/*' || '' }}